version: '3'
services:
    postgres:
        image: 'postgres:15-alpine'
        volumes:
            - '.:/application'
        environment:
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_DATABASE}
        ports:
            - '50004:5432'

    webserver:
        image: 'nginx:alpine'
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '50000:80'

    php-fpm:
        build:
            context: .
            dockerfile: docker/php-fpm/Dockerfile
        volumes:
            - .:/application
            - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.3/fpm/conf.d/99-overrides.ini

    adminer:
        image: adminer
        ports:
            - '8080:8080'
